name: Donelist generate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  donelist_generate:
    name: Log release history
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date '+%Y-%m-%d' --date '33 hours')"

    - name: Register issue
      uses: imjohnbo/issue-bot@v2.3
      with:
        title: ${{ steps.date.outputs.date }}_${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.url }}
        assignees: "tanaka-yohei" # Github Account name without @.
        labels: "release"
        pinned: false
        close-previous: true
        template: ".github/ISSUE_TEMPLATE/RELEASE.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
